[book]
authors = ["Moonsong-Labs"]
language = "en"
multilingual = false
src = "src"
title = "foundry-zksync book"
description = "A book on all things foundry-zksync"

[build]
create-missing = false

[preprocessor.external-links]

[output.html]
git-repository-url = "https://github.com/matter-labs/foundry-zksync-book"
edit-url-template = "https://github.com/matter-labs/foundry-zksync-book/edit/main/{path}"
default-theme = "ayu"
additional-js = ["src/static/solidity.min.js"]
cname = "96ba0f25.book-3fk.pages.dev"
additional-css = ["src/static/custom.css"]

[output.html.fold]
enable = true
level = 1
