name: deploy

permissions: {}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install bun
        uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: vocs
        run: bun install

      - name: Check links
        working-directory: vocs
        continue-on-error: true
        run: |
          bun check-links.ts
          cat links-report.json | jq
          if [ $? -ne 0 ]; then
            exit 1
          fi

      - name: Build Vocs
        working-directory: vocs
        run: bun run build

      - name: Publish
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: foundry-book
          directory: vocs/docs/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
